CREATE DATABASE IF NOT EXISTS radioapp;

USE radioapp;

CREATE TABLE users (
  id INT(11) NOT NULL AUTO_INCREMENT, 
  PRIMARY KEY(id)
  name VARCHAR(45) DEFAULT NULL,
  lastName VARCHAR(45) DEFAULT NULL, 
  email VARCHAR(50) DEFAULT NULL,
  password VARCHAR(100) DEFAULT NULL
);